### ISSUE TITLE
Add License information

### ISSUE THREAD

**Issue by Cuperino** [soxofaan/scrollocue#1]
First of all, this is a really nice and simple teleprompter solution! My sincere congratulations. I can visualize some people, such as audio book readers, preferring this over traditional alternatives.

You should specify a license to your source code. Even when you've released your code publicly, copyright laws still apply and it isn't globally implied what rights other people have when making use of your code. Also, most open source licenses also have a "no warranty" claim that helps protect you against other people's misuse of your code.

**Comment by soxofaan** [comment]
Thanks :smile: 
This is a pretty old project, I didn't know this was still used

I added MIT license

**Comment by Cuperino** [comment]
Awesome! Yeah, there's been an increase in the number of people looking for teleprompter solutions since quarantines began all over the world.

I wrote and maintain a more traditional teleprompter solution called [Imaginary Teleprompter](https://github.com/ImaginarySense/Imaginary-Teleprompter) and came across your library doing a general search for teleprompter on GitHub. I'm fairly sure that if you make the text in your demo editable and containerize the library as a standalone app, it would get a fair amount of users since some people are more interested on keeping their pace as they read while others are more interested on keeping their eyes at the center.
